### PR TITLE
feat(*): update ui-router/angular dependency that supports angular 8

### PR DESCRIPTION
**Pull request by wawyed**

### CODE REVIEW

**Comment by Pittan** [comment]
@wawyed 
Hi! Could you re-run this CI job again? Maybe this time will succeed, thanks!

**Comment by wawyed** [comment]
Will reopen to re-run CI job

**Comment by wawyed** [comment]
https://github.com/ui-router/angular-hybrid/pull/331

**Comment by epicoxymoron** [comment]
Thanks for addressing this - is there an ETA on when it might land in a release?

**Comment by wawyed** [comment]
Hopefully later today.

**Comment by wawyed** [comment]
@epicoxymoron new version is out

**Pull request closed without merging**
