### PR TITLE
feat: Angular 17 support

### PR DESCRIPTION
**Pull request by vanhorickanthony**
This PR adds support for Angular v17.

Fixes https://github.com/ui-router/angular-hybrid/issues/594.

### CODE REVIEW

**Comment by wawyed** [comment]
@lievenjanssen  test-downstream needs to be sorted out

**Comment by vanhorickanthony** [comment]
@wawyed  The downstream test fails because of incompatible peer dependencies between version 16 and 17 - you can however successfully run the tests locally by substituting the hybrid UI router dependency for the local version.
The tests currently use the latest released version which is still V16 - while the version being tested is V17.

**Comment by wawyed** [comment]
You need to create a PR here such as https://github.com/ui-router/sample-app-angular-hybrid/pull/914

**Comment by kburczyk** [comment]
@vanhorickanthony Thank you very much, for this update. I'm desperately waiting for it. Do you know, when it will be merged?

**Comment by vanhorickanthony** [comment]
@wawyed Alright, thanks. A PR has been created as requested, and can be tracked here https://github.com/ui-router/sample-app-angular-hybrid/pull/916.

**Comment by lievenjanssen** [comment]
@wawyed is the requested PR on the sample app ok? Is there anything still needed to move on with merging this?

**Comment by wawyed** [comment]
> @wawyed is the requested PR on the sample app ok? Is there anything still needed to move on with merging this?

Just trying to figure out why is it failing now.

**Pull request merged**
