### PR TITLE
feat(*): update ui-router/angular dependency that supports angular 8

### PR DESCRIPTION
**Pull request by wawyed**

### CODE REVIEW

**Comment by Pittan** [comment]
@christopherthielen
Hi, could you review this PR? Thanks!

**Comment by andsan** [comment]
Why is this not merged?

**Comment by eq-jxh188** [comment]
Would someone with write access please merge the PR?  Thanks!

**Comment by odikusar** [comment]
Duplicated with merged PR: https://github.com/ui-router/angular-hybrid/pull/325/files

**Comment by wawyed** [comment]
> 
> 
> Duplicated with merged PR: https://github.com/ui-router/angular-hybrid/pull/325/files

That PR is not merged. I closed it and opened this one instead since I needed to re-run CI.

**Pull request merged**
